// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletApp.Data;

#nullable disable

namespace WalletApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230505012707_UpdateIconForTransaction")]
    partial class UpdateIconForTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WalletApp.Core.Entities.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("icon_url");

                    b.HasKey("Id");

                    b.ToTable("icons", (string)null);
                });

            modelBuilder.Entity("WalletApp.Core.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateTransaction")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_transaction");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("IconId")
                        .HasColumnType("int")
                        .HasColumnName("icon_id");

                    b.Property<bool>("IsPending")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_pending");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("owner_id");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sender_name");

                    b.Property<double>("Sum")
                        .HasColumnType("double");

                    b.Property<int>("TypeTransaction")
                        .HasColumnType("int")
                        .HasColumnName("type_transaction");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.HasIndex("OwnerId");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("WalletApp.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WalletApp.Core.Entities.Transaction", b =>
                {
                    b.HasOne("WalletApp.Core.Entities.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId");

                    b.HasOne("WalletApp.Core.Entities.User", "Owner")
                        .WithMany("Transactions")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icon");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WalletApp.Core.Entities.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
